import type { FavoriteRecord } from "./types";
const NAME="neverita-features-v1", VERSION=1, FAVORITES="favorites", OUTBOX="outbox";
export interface FeatureMutation { clientMutationId:string; userId:string; kind:"favorite"|"cooking"|"shopping"; entityId:string; payload:Record<string,unknown>; state:"pending"|"processing"|"conflict"|"rejected"; result?:unknown; conflicts?:unknown[]; createdAt:string }
const req=<T>(r:IDBRequest<T>)=>new Promise<T>((ok,no)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});
const done=(t:IDBTransaction)=>new Promise<void>((ok,no)=>{t.oncomplete=()=>ok();t.onerror=()=>no(t.error);t.onabort=()=>no(t.error)});
export async function openFeatureDb(){const r=indexedDB.open(NAME,VERSION);r.onupgradeneeded=()=>{const db=r.result;const f=db.createObjectStore(FAVORITES,{keyPath:"key"});f.createIndex("by_user","userId");const o=db.createObjectStore(OUTBOX,{keyPath:"clientMutationId"});o.createIndex("by_user", "userId")};return req(r)}
export async function cacheFavorite(userId:string,row:FavoriteRecord){const db=await openFeatureDb(),tx=db.transaction(FAVORITES,"readwrite");tx.objectStore(FAVORITES).put({key:`${userId}:${row.id}`,userId,...row});await done(tx);db.close()}
export async function listCachedFavorites(userId:string){const db=await openFeatureDb(),tx=db.transaction(FAVORITES,"readonly");const rows=await req(tx.objectStore(FAVORITES).index("by_user").getAll(userId)) as Array<FavoriteRecord&{userId:string}>;await done(tx);db.close();return rows.filter(x=>!x.deleted_at)}
export function reduceFeatureMutations(rows:FeatureMutation[],next:FeatureMutation){if(next.kind==="cooking")return [...rows,next];const prior=rows.findLast(row=>row.userId===next.userId&&row.kind===next.kind&&row.entityId===next.entityId&&row.state==="pending");return prior?[...rows.filter(row=>row.clientMutationId!==prior.clientMutationId),next]:[...rows,next]}
export async function queueFeatureMutation(m:FeatureMutation){const rows=await listFeatureMutations(m.userId),reduced=reduceFeatureMutations(rows,m),db=await openFeatureDb(),tx=db.transaction(OUTBOX,"readwrite"),store=tx.objectStore(OUTBOX);for(const row of rows)if(!reduced.some(item=>item.clientMutationId===row.clientMutationId))store.delete(row.clientMutationId);store.put(m);await done(tx);db.close()}
export async function listFeatureMutations(userId:string){const db=await openFeatureDb(),tx=db.transaction(OUTBOX,"readonly");const rows=await req(tx.objectStore(OUTBOX).index("by_user").getAll(userId)) as FeatureMutation[];await done(tx);db.close();return rows}
export async function finishFeatureMutation(id:string){const db=await openFeatureDb(),tx=db.transaction(OUTBOX,"readwrite");tx.objectStore(OUTBOX).delete(id);await done(tx);db.close()}
