// Manual spec preparation: this checkout has no spec.mjs prepare command.
// Writes documentation only; never approves or implements the feature.
import fs from "node:fs";
import { renderInterview, writeInterview, readInterview } from "./interview.mjs";

const spec = JSON.parse(fs.readFileSync("spec.json", "utf8"));
const feature = spec.features.find(f => f.id === "sprint-r2-today-decision-engine");
if (feature.spec_approved || !["pending", "spec_ready"].includes(feature.status)) throw new Error("R2 already approved or started");
if (spec.features.find(f => f.id === feature.dependencies[0]).status !== "done") throw new Error("R1 not closed");
const decisions = {
  data_model: "Reutilizar PantryItemKnowledge, food_concepts, recetas/ingredientes del catálogo activo y favoritos propios. Proyección conservadora en lectura: concepto explícito o alias exacto único; nunca fuzzy ni backfill automático. Cache v3 privada y separada de v1. Nuevos campos/tablas/RPC solo aditivos; sin resets. R2 no indexa snapshots privados/importados aún sin contrato de catálogo (R3).",
  error_states: "Distinguir despensa vacía, sin conceptos utilizables, sin candidatos, catálogo ausente, error de lectura y desconexión. No fabricar recomendaciones. Retry explícito; conservar resultado anterior solo con etiqueta de antigüedad. Compra requiere red y confirmación explícita, transacción atómica y replay. Sin cuota de negocio para Hoy; límites técnicos antiabuso no consumen usage.",
  edge_cases: "Eliminar tombstones/empty/quantity=0 de disponibilidad; legacy conserva precisión desconocida. Agrupar ingredientes por concepto y sumar requerimientos exactos compatibles antes de comparar; sumar existencias exactas compatibles una sola vez. g/kg y ml/l convertibles; pack/unit/volumen/peso no se mezclan. Ingredientes ambiguos permanecen unknown; nunca contar un desconocido como faltante demostrado. No presumir sal/aceite básicos ni sustituir alimentos. Fecha civil local y cantidades de receta sin escalado de raciones.",
  auth_secrets: "Sesión/RLS delimitan inventario, favoritos, cache y compra. El request no acepta usuario, inventario, plan ni scores. Cache HTTP privada no-store; no cache SW compartido. Logout/cambio de usuario descarta respuesta y datos de Hoy. Sin LLM ni nuevas credenciales. TTMD solo IDs de evento/sesión efímeros y tiempos; sin userId, nombres, recetas, inventario, hash ni texto privado.",
  external_contracts: "GET /api/recommendations/today?date=YYYY-MM-DD devuelve contrato today-v2 con main<=3, secondary<=3, availability/reasons/missing/unknown, snapshotKey opaca, versiones y estados explícitos. date sirve solo para fecha civil; no ownership. POST /api/recommendations/shopping {recipeId,snapshotKey,clientMutationId} recalcula faltantes de servidor; snapshot cambiado=409, replay devuelve mismos IDs. Nunca invocar begin_recipe_suggestion/consume_usage de v1. CTA Cocinar esto abre detalle existente, sin consumir stock ni iniciar sesión de cocina R4.",
  ui_states: "PRODUCT_V3=true convierte /app en Hoy automático. Referencias 06/10, tokens R0/R1. Máximo tres decisiones principales compactas: primera tarjeta y CTA visibles a 393x852 antes de bloques secundarios; no exigir que tres tarjetas completas quepan. Onboarding saltables solo en cuenta sin items activos y no visto por ese usuario/dispositivo. Ejemplo explícito aislado sin datos escritos. Empty enlaza a /app/add-purchase y /app/recipes/import. Error/offline honestos; teclado, 44px, foco, reduced motion y sin overflow a320.",
  rollback_compat: "Flag ausente/false conserva /app InventoryApp, endpoint y cuota legacy v1 y navegación v2. API v3 responde404 con flagfalse. Sin cambios OCR, import, billing, cooking, planificación, proveedores, Pro ni R3-R8. No despliegue/activación ni reset/backfill destructivo. Compras reutilizan semántica actual; procedencia y agrupación avanzada quedan R5.",
  tests: "Unit domain para presencia/cantidad/unidades/dedup/ranking/frescura/cache; web para contrato, errores, onboarding y métricas; SQL/RLS dos usuarios, compra atómica/replay, permisos, cache y usage invariable. Playwright con DB local: ready/quantity_to_check/missing_one/missing_many/unknown/empty, estimates, Free agotado, compras, dos usuarios y flagfalse. Capturas reales320/393 y comparación06/10. Gates harness, domain typecheck/tests, build, DB lint/pgTAP, instalación frozen si cambia lockfile. Smoke real pendiente R1 no se presenta como completado.",
};
const acceptance = [
  "Con PRODUCT_V3=true, abrir /app autenticado calcula Hoy automáticamente, sin pulsar Actualizar sugerencias. Con flag ausente/false se conserva v2; las API v3 devuelven 404 y las cuotas legacy no se alteran.",
  "Hoy devuelve y muestra como máximo tres opciones principales y tres secundarias distintas. A393x852 se ve encabezado, primera propuesta y su CTA antes de cualquier bloque secundario. A320 no hay overflow; controles>=44px, teclado/foco y reduced-motion verificables.",
  "El universo R2 contiene recetas del catálogo activo con ingredientes e instrucciones no vacíos. Favoritos propios influyen si su recipe_id pertenece a ese catálogo. Snapshots privados/importados no se exponen ni se convierten en catálogo global; su integración corresponde a R3.",
  "Resolver ingrediente por food_concept_id explícito o alias/nombre exacto único usando normalización caso/acentos/espacios de R1; colisiones quedan unknown. No fuzzy/substring/LLM ni normalización que escriba en inventario. Pantry proposed/unknown y precision legacy no se elevan a confirmed/exact.",
  "Items eliminados, estado empty/absent o exact quantity=0 no aportan presencia ni frescura. Pantry con concepto confirmado y presencia positiva sirve aunque no tenga cantidad exacta; pantry ambiguo no justifica Tienes todo.",
  "Agrupar líneas de receta por concepto; sumar cantidades positivas inequívocas de unidades compatibles antes de evaluar y sumar cada item disponible una sola vez. Unidad exacta en g/kg o ml/l permite conversión; unit y pack solo misma unidad. No asumir contenido de packs, densidad ni equivalencia de alimento. Measure textual ambiguo o ausente queda cantidad por comprobar.",
  "have_enough exige requerimiento y stock exactos compatibles y stock>=total requerido. Presencia cualitativa o cantidad requerida no verificable produce have_presence_unknown_amount; exact insuficiente compatible es missing; unidad incompatible es unknown, sin afirmar suficiencia ni faltante numérico.",
  "Sin concepto inequívoco, el ingrediente queda unknown y se lista por su nombre de receta con copy Por comprobar. Ausencia de un concepto identificado en pantry utilizable es missing. No ignorar ingredientes básicos, opcionales no estructurados ni sustituirlos.",
  "Estado ready solo si todos los grupos son have_enough; quantity_to_check si no hay missing/unknown y algún grupo tiene presencia sin cantidad. missing_one/missing_many dependen de conceptos missing distintos; unknown sin missing tiene su propio estado. Si hay missing y unknown simultáneos, se muestran ambos conteos por separado.",
  "Cards ready muestran Tienes todo; quantity_to_check muestra Tienes los ingredientes y Cantidad por comprobar. Missing muestra Te falta1/Te faltanN deduplicados y Por comprobarN cuando proceda. Unknown usa Hay ingredientes por comprobar. No porcentajes, scores ni confidence numéricos en UI o respuesta v3.",
  "Orden determinista: ready, quantity_to_check, missing_one, missing_many (missingCount ascendente), unknown; dentro grupo unknownCount ascendente, frescura verificada antes de estimada antes de ninguna, favorito antes de no favorito y recipeId ASCII ascendente. R2 no usa recencia ni preferencias no persistidas. La versión recommendation cambia respecto al ranking inicial R0 si cambia su contrato.",
  "Frescura verificada: expiry_date_exact con source package/user/retailer y fecha civil entre hoy y hoy+2 inclusive. Puede decir Gasta primeroX; fechas pasadas nunca generan consejo de uso urgente y muestran Comprueba su estado si se mencionan. No inferir seguridad alimentaria.",
  "Frescura estimada: acquired_on válido + ventana documentada cuyo final está entre hoy y hoy+2 inclusive; solo señal débil y copy Buena opción para aprovecharX · conservación estimada. No Caduca/Gasta primero. Sin fecha, ventana pasada, source desconocido o expiry legacy no hay señal. No usar score de confianza inventado.",
  "También podrías aprovechar aparece únicamente con señal útil de frescura, excluye las principales y no ofrece recetas unknown. Si no hay candidatos adecuados desaparece. Razones retornadas se limitan a códigos semánticos documentados con alimentos públicos del concepto.",
  "Selección acotada y reproducible: hasta200 recetas con mayor número de conceptos de pantry coincidentes, desempate recipeId ASCII; integrar hasta50 favoritos propios del catálogo y completar hasta50 recetas iniciales del catálogo si no hay coincidencias. Deduplicar, max250. El ranking evalúa ingredientes completos del conjunto; no promete óptimo global del catálogo ni consulta N+1 por receta.",
  "GET /api/recommendations/today admite únicamente date civil válida opcional (fallback fecha civilEurope/Madrid del servidor). Respuesta200 {contract:today-v2,date,generatedAt,state:ready|empty_pantry|unresolved_pantry|no_candidates,main,secondary,snapshotKey,catalogVersion,matcherVersion,recommendationVersion}; main/secondary incluyen recipeId,name,availability,missingCount,unknownCount,quantityToCheck,missingIngredients,unknownIngredients,reasons. Sin aceptar userId/plan/inventario ni devolver private raw.",
  "GET errores:401 AUTH_REQUIRED,400 INVALID_REQUEST,409 CATALOG_NOT_READY,503 TODAY_UNAVAILABLE retryable. Sin catálogo activo no responder vacío como si fuera despensa vacía. HTTP private,no-store; respuesta visible distingue carga/error/catálogo/sinresultados con Reintentar.",
  "Cache privada por usuario con TTL<=60min y clave que cubre pantry relevante, conceptos/aliases, catálogo, favoritos, fecha civil y matcher/recommendationVersion. Mismos inputs mismo ranking; cantidad/estado/tombstone/normalización/frescura/favorito/catálogo/día invalida. Leer resultado recomprueba sesión; usuario distinto no reutiliza cache. snapshotKey no sustituye ownership.",
  "Hoy nunca ejecuta consume_usage(recipe_suggestions), begin_recipe_suggestion ni crea/incrementa usage. Free con cuota legacy ya agotada recibe recomendaciones tras al menos seis cambios de pantry y reaperturas; contadores y OCR/import/billing permanecen intactos.",
  "Cocinar esto en ready o quantity_to_check abre /app/recipes/[id] existente; quantity_to_check conserva aviso antes de navegar. No descuenta stock ni registra comida. Unknown ofrece Revisar receta/Despensa. Modo cocina guiado queda R4.",
  "Añadir a la compra en recetas con missing presenta los faltantes actuales y pide confirmación explícita. POST /api/recommendations/shopping recibe solo {recipeId,snapshotKey,clientMutationId}; servidor recalcula bajo sesión y catálogo, rechaza snapshot distinto con409 SNAPSHOT_CONFLICT y devuelve {status:applied,itemIds}. No acepta nombres/cantidades del cliente.",
  "Compra escribe todos los conceptos faltantes de una receta en una sola transacción con IDs/clave idempotentes. Replay idéntico devuelve mismos IDs; mismo clientMutationId con otra receta/snapshot=409 MUTATION_CONFLICT. Exact insuficiente guarda déficit real en unidad canónica; falta sin cantidad exacta guarda quantity/unit null. Unknown nunca se añade automáticamente. Error/red perdida no muestra éxito ni deja escritura parcial; reintento mantiene mutationId.",
  "Tras compra aplicada se muestran confirmación y enlace /app/shopping-list. Repetir mismo envío no duplica filas. Un nuevo gesto confirmado tiene nueva mutationId (no implica agregación automática entre compras); lista/procedencia avanzada quedan R5.",
  "Despensa sin items activos muestra Aún no sabemos qué tienes con Añadir compra a /app/add-purchase y Trae una receta que te guste a /app/recipes/import en un toque. Items existentes sin conceptos utilizables muestran Revisa tu despensa con acceso real; no se inventan tres ejemplos como recomendaciones propias.",
  "Onboarding se muestra solo con cero items activos y estado no visto para usuario/dispositivo; se puede saltar y queda marcado visto al saltar o elegir entrada. Escanear ticket abre /app/scan; escribir abre /app/add-purchase; Ver ejemplo abre demostración claramente marcada y aislada sin escribir pantry/cache/compra. Cuentas migradas con items no reciben onboarding; cambio de cuenta no comparte estado.",
  "Offline no genera ranking nuevo ni permite compra. Un Hoy previamente cargado en la misma sesión puede mantenerse marcado Resultado anterior · Sin conexión y sin CTA de escritura; una recarga no soportada usa fallback PWA existente sin prometer Hoy offline completo. Al reconectar o volver desde cambio de pantry se solicita snapshot nuevo; outbox pendiente evita presentar ranking remoto como datos locales ya guardados.",
  "TTMD: inicio al entrar Hoy, fin una sola vez al mostrar primera propuesta accionable o salida empty/unresolved/no_candidates; error no emite éxito. Eventos CustomEvent neverita:today-metric {eventId,sessionId,phase:opened|decision_visible,outcome?,timestamp,durationMs?}, IDs efímeros sin persistencia ni PII; duración monotónica no negativa y StrictMode/retry no duplica fin. R2 instrumenta, no incorpora backend analytics nuevo.",
  "Pruebas unit/domain cubren alias ambiguo, deduplicación/suma, unidades, empty/tombstone/legacy, unknown frente a missing, orden estable permutando input, frescura exacta/estimada/pasada y cambios de cache. SQL prueba dos usuarios, privilegios, transacción/replay y contadores sin cambios. E2E cubre los estados principales, CTA real/compra, onboarding, errores/retry, offline, Freeagotado, flagfalse y TTMD sin PII.",
  "Capturas reales localhost320/393 con DB sintética aislada documentan comparación con06/10: encabezado, decisiones/razones/CTA, incertidumbre, empty y onboarding. No snapshots de maqueta como evidencia. Pasan gates harness, build, domain typecheck/tests, dblint y pgTAP. Ningún reset DB, producción, cambios destructivos ni implementación R3-R8.",
];
acceptance.push("Parser de cantidades de receta R2 limitado a un número positivo entero o decimal (coma/punto) seguido de g, kg, ml, l, unidad/unidades/unit o pack/packs; normalizar a g/ml/unit/pack. Fracciones, rangos, al gusto, envases con contenido y unidades no admitidas quedan por comprobar. Dentro de un concepto, requerimientos exactos de dimensiones distintas producen unknown; exactos más línea de cantidad desconocida nunca producen have_enough. Si hay una línea de cantidad desconocida y presencia positiva, el grupo permanece have_presence_unknown_amount sin afirmar un déficit numérico total; la ausencia de presencia sí sigue siendo missing.");
acceptance.push("La compra valida snapshot actual dentro de la transacción, incluyendo cambios concurrentes de pantry/catálogo, sin escribir parcialmente. Un replay ya aplicado se resuelve antes de comprobar el snapshot nuevo y devuelve los IDs originales incluso si cambió pantry después. snapshotKey referencia exclusivamente el resultado propio autorizado; no se acepta un snapshot de otra cuenta. 400 INVALID_REQUEST,401 AUTH_REQUIRED,404 RECIPE_NOT_FOUND,409 SNAPSHOT_CONFLICT|MUTATION_CONFLICT y503 SHOPPING_UNAVAILABLE distinguen los errores.");
acceptance.push("La selección consulta índices/conteos en DB y carga ingredientes completos solo de los candidatos acotados; no descarga las decenas de miles de recetas para filtrar en servidor/navegador. Orden y cardinalidad son comprobables con fixtures y benchmark local reproducible; registrar tiempos y tamaño del dataset sin convertir el benchmark en promesa de rendimiento de producción.");
const scope = [
  "apps/web/src/app/(auth)/app/page.tsx", "apps/web/src/components/today/**", "apps/web/src/lib/recommendations/**",
  "apps/web/src/app/api/recommendations/**", "apps/web/src/styles/product-v3.css", "apps/web/src/types/database.generated.ts",
  "packages/domain/src/recommendations/**", "packages/domain/src/recipes/**", "packages/domain/src/pantry/**", "packages/domain/src/index.ts",
  "supabase/migrations/**", "supabase/tests/**", "tests/**", "docs/**", "spec.json",
];
const dimensions = Object.fromEntries(Object.entries(decisions).map(([key, notes]) => [key, { addressed: true, notes }]));
writeInterview(feature, renderInterview(feature, {dimensions, acceptance, scope}, decisions).trimEnd() + "\n");
feature.title = feature.name;
feature.description = feature.objective;
feature.acceptance = acceptance;
feature.scope = scope;
feature.status = "spec_ready";
feature.manual_spec_ready = true;
feature.manual_spec_ready_at = new Date().toISOString();
feature.manual_spec_ready_reason = "Preparación manual: comando prepare ausente; ocho dimensiones resueltas y QA de contratos/casos límite documentada. Sin aprobación ni implementación.";
feature.spec_approved = false;
const dir = `spec/${feature.id}-${feature.name}`;
fs.mkdirSync(dir, {recursive: true});
fs.writeFileSync(`${dir}/proposal.md`, `# Sprint R2 — Propuesta para aprobación\n\nEstado: spec_ready; spec_approved: false. Solo documentación; R2 no implementado.\n\n${readInterview(feature).md}`);
fs.writeFileSync(`${dir}/requirements.md`, `# Sprint R2 — Requisitos propuestos (sin aprobar)\n\n${feature.objective}\n\n${acceptance.map((a,i)=>`R${i+1}. ${a}`).join("\n\n")}\n`);
fs.writeFileSync(`${dir}/design.md`, `# Sprint R2 — Diseño propuesto (sin aprobar)\n\n${Object.entries(decisions).map(([key,value])=>`## ${key}\n\n${value}`).join("\n\n")}\n\n## Scope propuesto\n\n${scope.map(p=>`- ${p}`).join("\n")}\n`);
fs.writeFileSync(`${dir}/tasks.md`, `# Sprint R2 — Checklist propuesto (sin aprobar)\n\n${acceptance.map((a,i)=>`- [ ] T${i+1} / R${i+1}: ${a}`).join("\n\n")}\n`);
fs.writeFileSync(`${dir}/qa.md`, `# QA del spec R2 — 2026-10-01\n\nRevisión manual del comportamiento frente al código R0/R1 y las ocho dimensiones del harness; no ejecución de producto.\n\n- Se distinguen presencia de suficiencia, unknown de missing y conceptos duplicados de unidades incompatibles.\n- Se fijan orden y desempate, horizonte civil de frescura de dos días, versión de cache y universo acotado; no promesa de ranking global.\n- API request/response/errores, replay y autorización de compra definidos. No reutilizar reserva de cuota v1.\n- Los CTAs usan rutas reales existentes. Cooking/recetas privadas/importación avanzada permanecen en sus sprints.\n- Onboarding, ejemplo y offline se delimitan sin prometer soporte que R1 no tiene. Métrica no requiere nuevos proveedores ni registra contenido.\n- Scope incluye estilos, tipos, dominio pantry, SQL/tests e index necesarios que faltaban en el plan inicial.\n- No queda decisión bloqueante sin comportamiento observable. Las elecciones conservadoras propuestas requieren aprobación del spec.\n- Smoke real pendiente R1 registrado en progress; no se considera validado por su cierre.\n\nLimitaciones aceptadas en esta propuesta: sin ranking de snapshots privados, sin recencia no disponible, sin equivalencias culinarias/porciones/packs, sin navegación Hoy nueva offline ni analytics externo.\n`);
fs.writeFileSync("spec.json", JSON.stringify(spec, null, 2) + "\n");
console.log(`${feature.id}: spec_ready, ${acceptance.length} criterios, sin aprobar`);
