import { describe, expect, it } from 'vitest';
import { buildCookingPlan, decimalSum, type CookingLot } from './plan';
import type { CookRecipe } from '../recipes/availability';
const concept = { id: 'egg', displayName: 'Huevos', aliases: ['huevo'] };
const recipe = (measure: string | null = '4 unit'): CookRecipe => ({ recipeRef: { kind: 'import', id: 'recipe' }, title: 'Huevos', ingredients: [{ name: 'Huevos', measure }], steps: ['Cocina'], reviewRequired: false, provenance: null, sourceUrl: null });
const lot = (patch: Partial<CookingLot> = {}): CookingLot => ({ id: 'lot', name: 'Huevos', version: 3, food_concept_id: 'egg', normalization_status: 'confirmed', deleted_at: null, stock_mode: 'exact', stock_state: null, quantity_precision: 'exact', quantity_exact: 16, quantity_unit: 'unit', expiry_date_exact: '2026-10-10', freshness_precision: 'exact', freshness_source: 'user', created_at: '2026-10-01', ...patch });
describe('conservative cooking plans', () => {
  it('allocates 4 of 16 and preserves exact remainder', () => { const line = buildCookingPlan(recipe(), [lot()], [concept])[0]; expect(line.mode).toBe('exact'); expect(line.proposedAfter).toBe('12 unit'); expect(line.allocations[0].after).toBe(12); });
  it('adds duplicate requirements and allocates FEFO once across lots', () => { const r = recipe('3 unit'); r.ingredients.push({ name: 'huevo', measure: '2 unit' }); const line = buildCookingPlan(r, [lot({ id: 'later', quantity_exact: 10, expiry_date_exact: null }), lot({ id: 'first', quantity_exact: 4 })], [concept])[0]; expect(line.required).toBe(5); expect(line.allocations.map(l => [l.inventoryItemId, l.consumption])).toEqual([['first', 4], ['later', 1]]); });
  it('does not saturate shortage or subtract an absent recipe quantity', () => { expect(buildCookingPlan(recipe('20 unit'), [lot()], [concept])[0]).toMatchObject({ mode: 'unresolved', insufficient: true, proposedAfter: 'Sin cambios' }); expect(buildCookingPlan(recipe(null), [lot()], [concept])[0].allocations[0].consumption).toBe(0); });
  it('proposes qualitative transitions without requiring arithmetic', () => { expect(buildCookingPlan(recipe(null), [lot({ stock_mode: 'qualitative', quantity_precision: 'unknown', quantity_exact: null, quantity_unit: null, stock_state: 'low' })], [concept])[0]).toMatchObject({ mode: 'qualitative', proposedAfter: 'Se acabó' }); });
  it('requires explicit selection for multiple qualitative lots and presence', () => { const p = lot({ stock_mode: 'presence', stock_state: 'present', quantity_precision: 'unknown', quantity_exact: null }); expect(buildCookingPlan(recipe(null), [p], [concept])[0].mode).toBe('unresolved'); expect(buildCookingPlan(recipe(null), [p, { ...p, id: 'other' }], [concept])[0].allowedActions).not.toContain('apply'); });
  it('unknown aliases, unconfirmed, empty, deleted and incompatible units never justify a deduction', () => { const ambiguous = [concept, { id: 'other', displayName: 'Huevos' }]; expect(buildCookingPlan(recipe(), [lot()], ambiguous)[0].allocations).toHaveLength(0); for (const change of [{ normalization_status: 'unknown' }, { stock_state: 'empty' }, { deleted_at: '2026-10-01' }, { quantity_exact: 0 }]) expect(buildCookingPlan(recipe(), [lot(change)], [concept])[0].allocations).toHaveLength(0); expect(buildCookingPlan(recipe(), [lot({ quantity_unit: 'g' })], [concept])[0].mode).toBe('unresolved'); });
  it('converts only compatible units and uses decimal arithmetic', () => { const r = recipe('0.1 g'); r.ingredients.push({ name: 'Huevos', measure: '0.2 g' }); expect(buildCookingPlan(r, [lot({ quantity_exact: 0.3, quantity_unit: 'g' })], [concept])[0].proposedAfter).toBe('0 g'); expect(decimalSum([0.3, -0.1, -0.2])).toBe(0); expect(buildCookingPlan(recipe('500 g'), [lot({ quantity_exact: 1, quantity_unit: 'kg' })], [concept])[0].proposedAfter).toBe('500 g'); });
  it('does not promote an estimated expiry to FEFO evidence', () => { const line = buildCookingPlan(recipe(), [lot({ id: 'estimate', freshness_precision: 'estimated', expiry_date_exact: '2026-01-01' }), lot({ id: 'verified', expiry_date_exact: '2026-12-01' })], [concept])[0]; expect(line.allocations[0].inventoryItemId).toBe('verified'); });
});
