import {expect,test} from "@playwright/test";

test.describe("favorites, cooking and shopping at 320px",()=>{
 test.skip(!process.env.RUN_LOCAL_SUPABASE_E2E,"requires local Supabase auth");
 test.use({viewport:{width:320,height:720}});
 test.beforeEach(async({page})=>{const email=`s8-${Date.now()}-${Math.random()}@example.test`;await page.goto("/signup");await page.getByLabel("Email").fill(email);await page.getByLabel("Contraseña").fill("sprint-eight-password");await page.getByRole("button",{name:/Crear cuenta/}).click();await page.goto("/login");await page.getByLabel("Email").fill(email);await page.getByLabel("Contraseña").fill("sprint-eight-password");await page.getByRole("button",{name:/Entrar/}).click();await expect(page).toHaveURL(/\/app/)});
 test("saves a recipe and keeps an offline recovery route",async({page,context})=>{let favorite:{id:string;recipe_id:string;snapshot:unknown;snapshot_version:number;version:number;saved_at:string;deleted_at:null}|null=null;await page.route("**/api/recipes/suggestions",r=>r.fulfill({json:{contract:"recipe-suggestions-v1",recipes:[{id:"r1",name:"Sopa",matchPercentage:100,matchedIngredients:["tomate"],missingIngredients:[],ingredientsWithMeasures:["1 ud tomate"],instructions:"Cocer"}],inventoryHash:"x",catalogVersion:"v",matcherVersion:"v",inventoryEmpty:false,cache:{hit:false,expiresAt:new Date().toISOString()}}}));await page.route("**/api/favorites",async r=>{if(r.request().method()==="GET")return r.fulfill({json:{favorites:favorite?[favorite]:[]}});const b=JSON.parse(r.request().postData()!);favorite={id:"f1",recipe_id:"r1",snapshot:b.snapshot,snapshot_version:1,version:1,saved_at:new Date().toISOString(),deleted_at:null};return r.fulfill({json:{client_mutation_id:b.client_mutation_id,status:"applied",code:"OK",result:favorite,conflicts:[]}})});await page.goto("/app/recipes");await page.getByRole("button",{name:"Guardar receta"}).click();await expect(page.getByRole("button",{name:"Guardada"})).toBeVisible();await page.goto("/app/favorites");await expect(page.getByRole("heading",{name:"Sopa"})).toBeVisible();await context.setOffline(true);await page.reload();await expect(page.getByRole("status")).toContainText("Sin conexión");await expect(page.getByRole("button",{name:"Reintentar conexión"})).toBeVisible();await context.setOffline(false)});
 test("shows derived and explicit shopping lines with complete mobile navigation",async({page})=>{await page.route("**/api/shopping-list",async r=>r.request().method()==="GET"?r.fulfill({json:{items:[]}}):r.fulfill({json:{client_mutation_id:"m",status:"applied",code:"OK",result:{id:"i",ingredient_key:null,name:"Leche",quantity:1,unit:"l",checked:false,version:1},conflicts:[]}}));await page.goto("/app/shopping-list");await page.getByLabel("Ingrediente").fill("Leche");await page.getByLabel("Cantidad").fill("1");await page.getByLabel("Unidad").fill("l");await page.getByRole("button",{name:"Añadir"}).last().click();await expect(page.getByText("Leche")).toBeVisible();await expect(page.getByRole("link",{name:"Favoritos"})).toBeVisible()});
});
