/* eslint-disable @next/next/no-img-element -- crop previews use local blob URLs */
"use client";
import { useEffect, useRef, useState } from "react";
import type { ReceiptDraft, ReceiptItem } from "@/lib/receipt/parser";
import { MAX_RECEIPT_IMAGE_BYTES } from "@/lib/receipt/image";
import styles from "./receipt-scanner.module.css";

type Stage = "select"|"crop"|"processing"|"review"|"confirming"|"confirmed";
type Crop = {x:number;y:number;width:number;height:number};
const freshCrop = {x:0,y:0,width:100,height:100};

async function cropImage(file: File, crop: Crop, rotation: number): Promise<File> {
  const bitmap = await createImageBitmap(file, { imageOrientation:"from-image" });
  const sx=bitmap.width*crop.x/100, sy=bitmap.height*crop.y/100, sw=bitmap.width*crop.width/100, sh=bitmap.height*crop.height/100;
  const rotated=rotation%180!==0; const canvas=document.createElement("canvas"); canvas.width=rotated?sh:sw; canvas.height=rotated?sw:sh;
  const ctx=canvas.getContext("2d"); if(!ctx) throw new Error("INVALID_IMAGE"); ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(rotation*Math.PI/180);ctx.drawImage(bitmap,sx,sy,sw,sh,-sw/2,-sh/2,sw,sh); bitmap.close();
  const blob=await new Promise<Blob|null>((resolve)=>canvas.toBlob(resolve,"image/jpeg",.88)); if(!blob||blob.size>MAX_RECEIPT_IMAGE_BYTES) throw new Error(blob?.size?"IMAGE_TOO_LARGE":"INVALID_IMAGE");
  return new File([blob],"receipt.jpg",{type:"image/jpeg"});
}

export function ReceiptScanner(){
 const [stage,setStage]=useState<Stage>("select"),[file,setFile]=useState<File|null>(null),[processedFile,setProcessedFile]=useState<File|null>(null),[preview,setPreview]=useState<string|null>(null),[crop,setCrop]=useState<Crop>(freshCrop),[rotation,setRotation]=useState(0),[draft,setDraft]=useState<ReceiptDraft|null>(null),[draftId,setDraftId]=useState(""),[requestId,setRequestId]=useState(""),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState("Selecciona una imagen para empezar."),[recovered,setRecovered]=useState(false);
 const cameraInput=useRef<HTMLInputElement>(null),fileInput=useRef<HTMLInputElement>(null),selectButton=useRef<HTMLButtonElement>(null),heading=useRef<HTMLHeadingElement>(null),confirming=useRef(false);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
 useEffect(()=>{if(stage!=="select")heading.current?.focus()},[stage]);
 useEffect(()=>{if(stage!=="crop")return;const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();setStage("select");setFile(null);setProcessedFile(null);setDraftId("");setRequestId("");window.setTimeout(()=>selectButton.current?.focus(),0)}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[stage]);
 function choose(selected:File|undefined){if(!selected)return;if(preview)URL.revokeObjectURL(preview);setFile(selected);setProcessedFile(null);setDraftId("");setRequestId("");setRecovered(false);setPreview(URL.createObjectURL(selected));setCrop(freshCrop);setRotation(0);setError(null);setStage("crop")}
 async function camera(){try{if(!navigator.mediaDevices?.getUserMedia)throw new Error();const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"}});stream.getTracks().forEach(t=>t.stop());cameraInput.current?.click()}catch{setNotice("La cámara no está disponible. Puedes seleccionar una imagen del dispositivo.");fileInput.current?.focus()}}
 async function submit(){if(!file)return;try{setError(null);const processed=processedFile??await cropImage(file,crop,rotation);const d=draftId||crypto.randomUUID(),r=requestId||crypto.randomUUID();setProcessedFile(processed);setDraftId(d);setRequestId(r);setStage("processing");const data=new FormData();data.set("image",processed);data.set("draftId",d);data.set("requestId",r);data.set("locale",navigator.language||"es-ES");const response=await fetch("/api/ocr",{method:"POST",body:data});const body=await response.json();if(!response.ok)throw Object.assign(new Error(body.message),{code:body.code,retryable:body.retryable});setDraft(body.draft);setStage("review")}catch(e){setStage("crop");setError(e instanceof Error?e.message:"No se pudo leer el ticket")}}
 async function recover(){try{setError(null);setStage("processing");const response=await fetch("/api/ocr/recover",{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.message);setDraftId(body.draftId);setRequestId("");setDraft(body.draft);setRecovered(true);setStage("review")}catch(e){setStage("select");setError(e instanceof Error?e.message:"No se pudo recuperar el ticket")}}
 function update(index:number,key:keyof ReceiptItem,value:string|boolean){if(!draft)return;const items=draft.items.map((line,i)=>i===index?{...line,[key]:value}:line);setDraft({...draft,items})}
 function addLine(){if(!draft)return;setDraft({...draft,items:[...draft.items,{lineId:crypto.randomUUID(),rawText:"Añadida manualmente",name:"",quantity:"1",unit:"unit",unitPrice:null,totalPrice:null,confidence:null,accepted:true}]})}
 async function confirm(){if(!draft||confirming.current)return;confirming.current=true;setError(null);setStage("confirming");try{const response=await fetch("/api/ocr/confirm",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({draftId,lines:draft.items})});const body=await response.json();if(!response.ok){setError(body.message);setStage("review");return}setStage("confirmed")}finally{confirming.current=false}}
 return <div className={styles.shell}><nav className={styles.nav}><strong>Neverita · Ticket</strong><a href="/app">Inventario</a></nav><main className={styles.main}>
  <h1 ref={heading} tabIndex={-1}>{stage==="select"?"Escanea tu compra":stage==="crop"?"Recorta el ticket":stage==="processing"?"Leyendo ticket":stage==="review"?"Revisa cada línea":stage==="confirming"?"Guardando compra":"Compra añadida"}</h1>
  <p className={styles.lede}>Tú decides qué entra en el inventario. La imagen se guarda de forma privada.</p>
  <section className={styles.panel} aria-busy={stage==="processing"||stage==="confirming"}>
  {stage==="select"&&<><div className={styles.actions}><button className={styles.button} onClick={camera}>Usar cámara</button><button ref={selectButton} className={styles.secondary} onClick={()=>fileInput.current?.click()}>Seleccionar archivo</button></div><button className={`${styles.secondary} ${styles.recover}`} onClick={recover}>Retomar última revisión sin nuevo escaneo</button><input ref={cameraInput} className={styles.hidden} type="file" aria-label="Foto del ticket desde la cámara" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>choose(e.target.files?.[0])}/><input ref={fileInput} className={styles.hidden} type="file" aria-label="Imagen del ticket" accept="image/jpeg,image/png,image/webp" onChange={e=>choose(e.target.files?.[0])}/><p className={styles.status} role="status">{notice}</p></>}
  {stage==="crop"&&preview&&<><img className={styles.preview} src={preview} alt="Vista previa del ticket"/><p className={styles.hint}>Ajusta el recorte con el teclado o los controles. Pulsa Escape para cancelar.</p><div className={styles.cropGrid}>{(["x","y","width","height"] as const).map(k=><label key={k}>{k==="x"?"Izquierda":k==="y"?"Arriba":k==="width"?"Ancho":"Alto"}<input type="range" min="0" max={k==="x"?100-crop.width:k==="y"?100-crop.height:100-(k==="width"?crop.x:crop.y)} value={crop[k]} disabled={processedFile!==null} onChange={e=>setCrop({...crop,[k]:Number(e.target.value)})}/></label>)}</div><div className={styles.actions}><button className={styles.secondary} disabled={processedFile!==null} onClick={()=>setRotation((rotation+90)%360)}>Rotar 90°</button><button className={styles.button} onClick={submit}>{processedFile?"Reintentar solicitud":"Usar este recorte"}</button><button className={styles.secondary} onClick={()=>{setStage("select");setFile(null);setProcessedFile(null);setDraftId("");setRequestId("");window.setTimeout(()=>selectButton.current?.focus(),0)}}>Cancelar</button></div></>}
  {(stage==="processing"||stage==="confirming")&&<><div className={styles.spinner}/><p role="status" aria-live="polite">{stage==="processing"?"Procesando la imagen…":"Confirmando los artículos…"}</p></>}
  {stage==="review"&&draft&&<>{recovered&&<p className={styles.status} role="status">Ticket reinterpretado sin consumir otra lectura OCR. Revisa cada artículo antes de confirmar.</p>}<p>{draft.merchant||"Comercio sin reconocer"}{draft.total?` · Total ${draft.total} ${draft.currency||""}`:""}</p>{draft.items.map((line,i)=><fieldset className={styles.line} key={line.lineId}><legend>Línea {i+1}</legend><p className={styles.raw}>{line.rawText}</p><label>Nombre<input value={line.name??""} onChange={e=>update(i,"name",e.target.value)}/></label><label>Cantidad<input inputMode="decimal" value={line.quantity??""} onChange={e=>update(i,"quantity",e.target.value)}/></label><label>Unidad<input value={line.unit??""} onChange={e=>update(i,"unit",e.target.value)}/></label><label>Precio unitario<input inputMode="decimal" value={line.unitPrice??""} onChange={e=>update(i,"unitPrice",e.target.value||null as never)}/></label><label>Precio total<input inputMode="decimal" value={line.totalPrice??""} onChange={e=>update(i,"totalPrice",e.target.value||null as never)}/></label><label className={styles.check}><input type="checkbox" checked={line.accepted} onChange={e=>update(i,"accepted",e.target.checked)}/>Incluir</label></fieldset>)}{draft.unrecognizedLines.length>0&&<details><summary>Texto no reconocido</summary><p className={styles.unknown}>{draft.unrecognizedLines.join("\n")}</p></details>}<div className={styles.actions}><button className={styles.secondary} onClick={addLine}>Añadir línea</button><button className={styles.button} onClick={confirm}>Confirmar artículos</button></div></>}
  {stage==="confirmed"&&<p className={styles.confirmed} role="status">Los artículos se guardaron una sola vez. <a href="/app">Ver inventario</a></p>}
  {error&&<p className={`${styles.status} ${styles.error}`} role="alert">{error}</p>}
  </section><small>Solicitud: {requestId||"—"}</small></main></div>
}
