"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { getItem } from "@/lib/inventory/db";
import { deleteLocalItem, discardConflict, restoreLocalItem, retryWithRemoteVersion, updatePantryItem } from "@/lib/inventory/repository";
import { syncInventory } from "@/lib/inventory/sync";
import { createBrowserSupabaseClient } from "@/lib/supabase/browser";
import { isCivilDate, purchasedLabel } from "@/lib/inventory/dates";
import type { LocalInventoryItem } from "@/lib/inventory/types";
import type { Candidate } from "@/lib/normalization/contracts";

export function PantryItemEditor({ userId, itemId }: { userId: string; itemId: string }) {
  const router = useRouter(); const active = useRef(true); const dirty = useRef(false); const [item, setItem] = useState<LocalInventoryItem | null>(null); const [error, setError] = useState<string | null>(null); const [status, setStatus] = useState<"pending" | "saved" | null>(null); const [undo, setUndo] = useState(false);
  const [mode, setMode] = useState<"qualitative" | "exact">("qualitative"); const [state, setState] = useState<"plenty" | "some" | "low" | "empty">("some"); const [quantity, setQuantity] = useState(""); const [unit, setUnit] = useState("unit"); const [expiry, setExpiry] = useState("");
  const [conceptId, setConceptId] = useState<string | null>(null); const [conceptQuery, setConceptQuery] = useState(""); const [concepts, setConcepts] = useState<Candidate[]>([]);
  const hydrate = useCallback((row: LocalInventoryItem) => { if (!active.current || row.userId !== userId) return; setItem(row); if (dirty.current) return; const qualitative = row.stockState === "plenty" || row.stockState === "some" || row.stockState === "low" || row.stockState === "empty" ? row.stockState : "some"; setMode(row.stockMode === "exact" ? "exact" : "qualitative"); setState(qualitative); setQuantity(row.quantityExact?.toString() ?? ""); setUnit(row.quantityUnit ?? "unit"); setExpiry(row.expiryDateExact ?? ""); setConceptId(row.foodConceptId ?? null); }, [userId]);
  const load = useCallback(async () => { const row = await getItem(userId, itemId); if (row) hydrate(row); }, [hydrate, itemId, userId]);
  const synchronize = useCallback(async () => { if (!navigator.onLine || !active.current) return; try { await syncInventory(userId, createBrowserSupabaseClient(), () => active.current); await load(); } catch { if (active.current) setError("No se pudo guardar el cambio. Puedes reintentar sin perderlo."); } }, [load, userId]);
  useEffect(() => { active.current = true; void load().then(synchronize); const online = () => void synchronize(); window.addEventListener("online", online); return () => { active.current = false; window.removeEventListener("online", online); }; }, [load, synchronize]);
  useEffect(() => { if (!undo) return; let remaining = 8000; let started = performance.now(); let timeout: number | null = null; const finish = () => { setUndo(false); void synchronize().finally(() => router.push("/app/pantry")); }; const arm = () => { started = performance.now(); timeout = window.setTimeout(finish, remaining); }; const visibility = () => { if (document.visibilityState === "hidden") { remaining -= performance.now() - started; if (timeout) window.clearTimeout(timeout); timeout = null; } else arm(); }; arm(); document.addEventListener("visibilitychange", visibility); return () => { if (timeout) window.clearTimeout(timeout); document.removeEventListener("visibilitychange", visibility); }; }, [router, synchronize, undo]);
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); setStatus(null); const form = new FormData(event.currentTarget); try { const exactQuantity = Number(quantity); if (mode === "exact" && (!Number.isFinite(exactQuantity) || exactQuantity < 0)) throw new Error("VALIDATION_ERROR"); if (expiry && !isCivilDate(expiry)) throw new Error("VALIDATION_ERROR"); const next = await updatePantryItem(userId, itemId, { name: String(form.get("name") ?? ""), notes: String(form.get("notes") ?? "") || null, location: (form.get("location") || null) as LocalInventoryItem["location"], stockMode: mode, stockState: state, quantityExact: mode === "exact" ? exactQuantity : null, quantityUnit: mode === "exact" ? unit : null, expiryDateExact: expiry || null, foodConceptId: conceptId }); if (active.current) { setItem(next); setStatus("pending"); } if (navigator.onLine) { await synchronize(); const canonical = await getItem(userId, itemId); if (canonical?.syncState === "synced" && active.current) { dirty.current = false; hydrate(canonical); setStatus("saved"); } } } catch { if (active.current) setError("Revisa el nombre, la cantidad y las fechas."); } }
  async function remove() { setError(null); await deleteLocalItem(userId, itemId); if (active.current) setUndo(true); }
  async function restore() { try { const restored = await restoreLocalItem(userId, itemId); if (active.current) { setItem(restored); setUndo(false); setStatus("pending"); } await synchronize(); } catch { if (active.current) setError("El alimento cambió en otro lugar. Revisa ambos valores antes de continuar."); } }
  async function searchConcepts() { try { const response = await fetch(`/api/ocr/v2/concepts?q=${encodeURIComponent(conceptQuery)}`); const body = await response.json(); if (active.current) setConcepts(response.ok ? body.concepts : []); } catch { if (active.current) setError("No se pudo buscar el concepto."); } }
  async function discard() { await discardConflict(userId, itemId); dirty.current = false; await load(); setError(null); }
  async function retry() { await retryWithRemoteVersion(userId, itemId); setStatus("pending"); await synchronize(); }
  if (!item) return <main className="pantry-editor"><p role="status">Cargando alimento…</p></main>;
  return <main className="pantry-editor"><Link href="/app/pantry">← Despensa</Link><p className="product-v3-kicker">Editar alimento</p><h1>{item.name}</h1>{item.acquiredOn && <p>{purchasedLabel(item.acquiredOn, item.acquiredOnSource === "receipt" ? "receipt" : "user")}</p>}
    {item.syncState === "conflict" && item.remoteSnapshot && <section className="pantry-conflict" aria-labelledby="conflict-title"><h2 id="conflict-title">Hay dos versiones</h2><p>Tu cambio: {item.name} · {item.stockState ?? item.quantityExact}</p><p>En otro dispositivo: {item.remoteSnapshot.name} · {item.remoteSnapshot.stock_state ?? item.remoteSnapshot.quantity_exact}</p><div><button type="button" onClick={discard}>Usar la otra versión</button><button type="button" onClick={retry}>Reintentar con mi cambio</button></div></section>}
    {undo ? <div className="pantry-undo" role="status"><span>Alimento eliminado.</span><button type="button" onClick={restore}>Deshacer</button></div> : <form onSubmit={save} onChange={() => { dirty.current = true; }}><label>Nombre<input name="name" defaultValue={item.name} minLength={1} maxLength={120} required /></label><label>Ubicación<select name="location" defaultValue={item.location ?? ""}><option value="">Por ubicar</option><option value="fridge">Nevera</option><option value="pantry">Armario</option><option value="freezer">Congelador</option></select></label>
      <fieldset><legend>Concepto culinario</legend><div className="review-other"><input aria-label="Buscar concepto" value={conceptQuery} onChange={(event) => setConceptQuery(event.target.value)} /><button type="button" onClick={searchConcepts}>Buscar</button>{concepts.map((concept) => <button type="button" aria-pressed={conceptId === concept.foodConceptId} key={concept.foodConceptId} onClick={() => { dirty.current = true; setConceptId(concept.foodConceptId); setConceptQuery(concept.displayName); }}>{concept.displayName}</button>)}</div></fieldset>
      <fieldset><legend>Cantidad</legend><div className="pantry-segmented"><button type="button" aria-pressed={mode === "qualitative"} onClick={() => { dirty.current = true; setMode("qualitative"); }}>Estado</button><button type="button" aria-pressed={mode === "exact"} onClick={() => { dirty.current = true; setMode("exact"); }}>Exacta</button></div>{mode === "qualitative" ? <div className="pantry-states">{([['plenty','Bastante'],['some','Algo'],['low','Poco'],['empty','Se acabó']] as const).map(([value, label]) => <button type="button" key={value} aria-pressed={state === value} onClick={() => { dirty.current = true; setState(value); }}>{label}</button>)}</div> : <div className="pantry-exact"><label>Número<input inputMode="decimal" value={quantity} onChange={(event) => { dirty.current = true; setQuantity(event.target.value); }} required /></label><label>Unidad<input value={unit} onChange={(event) => { dirty.current = true; setUnit(event.target.value); }} required /></label></div>}</fieldset>
      <label>Fecha exacta declarada por ti<input type="date" value={expiry} onChange={(event) => setExpiry(event.target.value)} /></label><label>Nota<textarea name="notes" defaultValue={item.notes ?? ""} rows={3} /></label>{error && <p className="pantry-alert" role="alert">{error} <button type="button" onClick={synchronize}>Reintentar</button></p>}{status === "pending" && <p role="status">Cambio pendiente de guardar.</p>}{status === "saved" && <p role="status">Cambio guardado.</p>}<button className="purchase-confirm" type="submit">Guardar cambios</button><button className="pantry-delete" type="button" onClick={remove}>Eliminar de la despensa</button></form>}
  </main>;
}
