"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { Candidate, ConfirmDecision, ReviewLine } from "@/lib/normalization/contracts";
import { localCivilDate } from "@/lib/inventory/dates";

type ReviewResponse = { lines: ReviewLine[]; decisions?: ConfirmDecision[]; purchaseDate?: string | null };
export function PurchaseReview({ draftId, pending = false }: { draftId: string; pending?: boolean }) {
  const router = useRouter(); const [lines, setLines] = useState<ReviewLine[]>([]); const [decisions, setDecisions] = useState<Record<string, ConfirmDecision>>({});
  const [purchaseDate, setPurchaseDate] = useState(localCivilDate()); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState<string | null>(null);
  const [otherLine, setOtherLine] = useState<string | null>(null); const [conceptQuery, setConceptQuery] = useState(""); const [concepts, setConcepts] = useState<Candidate[]>([]); const submittingRef = useRef(false);
  const decisionsRef = useRef<Record<string, ConfirmDecision>>({}); const persistQueue = useRef(Promise.resolve());
  const load = useCallback(async () => { setLoading(true); setError(null); try { let response = await fetch(`/api/ocr/v2/drafts/${draftId}`, { cache: "no-store" }); if (!pending && !response.ok) response = await fetch("/api/ocr/v2/normalize", { method: "POST", headers: { "content-type": "application/json", "x-client-civil-date": localCivilDate() }, body: JSON.stringify({ draftId }) }); const body = await response.json() as ReviewResponse & { message?: string }; if (!response.ok) throw new Error(body.message ?? "No se pudo preparar la revisión");
      setLines(body.lines); const defaults = Object.fromEntries(body.lines.map((line) => [line.lineId, { lineId: line.lineId, decision: line.resolution === "resolved" ? "accept" : "unknown", ...(line.foodConceptId ? { foodConceptId: line.foodConceptId } : {}), displayName: line.displayName } satisfies ConfirmDecision])) as Record<string, ConfirmDecision>;
      for (const persisted of body.decisions ?? []) if (defaults[persisted.lineId]) defaults[persisted.lineId] = persisted; decisionsRef.current = defaults; setDecisions(defaults);
      const acquired = body.lines[0]?.purchase?.acquiredOn ?? body.purchaseDate; if (acquired) setPurchaseDate(acquired);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo preparar la revisión"); } finally { setLoading(false); } }, [draftId, pending]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const selected = useMemo(() => Object.values(decisions).filter((line) => pending ? line.decision === "accept" || line.decision === "omit" : line.decision !== "omit").length, [decisions, pending]);
  async function persist(next: Record<string, ConfirmDecision>) { if (pending) return; const response = await fetch(`/api/ocr/v2/drafts/${draftId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ decisions: Object.values(next) }) }); if (!response.ok) throw new Error("No se pudo conservar la decisión"); }
  function update(lineId: string, patch: Partial<ConfirmDecision>) { const next = { ...decisionsRef.current, [lineId]: { ...decisionsRef.current[lineId], ...patch } }; decisionsRef.current = next; setDecisions(next); if (!pending) persistQueue.current = persistQueue.current.catch(() => undefined).then(() => persist(next)).catch(() => { setError("La decisión queda en pantalla, pero no se pudo guardar. Reintenta antes de salir."); }); }
  async function searchConcepts() { if (conceptQuery.trim().length < 2) return; try { const response = await fetch(`/api/ocr/v2/concepts?q=${encodeURIComponent(conceptQuery)}`); const body = await response.json(); setConcepts(response.ok ? body.concepts : []); } catch { setError("No se pudo buscar. Puedes mantener un nombre libre como desconocido."); } }
  async function confirm() { if (submittingRef.current) return; submittingRef.current = true; setSubmitting(true); setError(null); try {
      await persistQueue.current;
      if (pending) { for (const line of lines) { const decision = decisions[line.lineId]; if (!decision || decision.decision === "unknown") continue; const response = await fetch(`/api/ocr/v2/drafts/${draftId}/lines/${line.lineId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ clientMutationId: crypto.randomUUID(), expectedVersion: line.version, decision: decision.decision === "omit" ? "omit" : "resolve", foodConceptId: decision.foodConceptId, displayName: decision.displayName }) }); const body = await response.json(); if (!response.ok) throw new Error(body.code === "SYNC_CONFLICT" ? "Este alimento cambió en otro lugar. Conservamos ambos valores para que elijas." : body.message); } }
      else { const response = await fetch("/api/ocr/v2/confirm", { method: "POST", headers: { "content-type": "application/json", "x-client-civil-date": localCivilDate() }, body: JSON.stringify({ draftId, normalizerVersion: "receipt-normalizer-v2", lines: Object.values(decisions), purchaseDate }) }); const body = await response.json(); if (!response.ok) throw new Error(body.message); }
      router.push("/app/pantry"); router.refresh();
    } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo guardar. Reintenta."); if (pending) await load(); } finally { submittingRef.current = false; setSubmitting(false); } }
  const fallbackDate = lines[0]?.purchase?.source === "user";
  return <main className="purchase-review"><p className="product-v3-kicker">Revisar ticket</p><h1>{pending ? "Completa lo pendiente" : "Solo lo dudoso"}</h1><p className="product-v3-lead">{pending ? "Estos alimentos siguen activos en tu despensa. Resolverlos actualiza la fila original." : "Las coincidencias claras ya están seleccionadas. Elige qué hacer con las demás."}</p>
    {!pending && <label className="review-purchase-date">Fecha de compra<input type="date" value={purchaseDate} max={localCivilDate()} onChange={(event) => setPurchaseDate(event.target.value)} required /><small>{fallbackDate ? "El ticket no mostraba una fecha fiable; usamos tu fecha local de confirmación." : "Fecha leída del ticket. Corrígela si hace falta."}</small></label>}
    {loading && <p role="status">Preparando revisión…</p>}{error && <p className="pantry-alert" role="alert">{error} <button type="button" onClick={load}>Reintentar</button></p>}
    <div className="review-lines">{lines.map((line) => { const choice = decisions[line.lineId]; return <fieldset key={line.lineId} className={`review-line review-${line.resolution}`}><legend>{line.resolution === "resolved" ? "Resuelto" : line.resolution === "doubtful" ? "Dudoso" : "Sin identificar"}</legend><p className="review-raw">{line.rawName}</p><input aria-label={`Nombre para ${line.rawName}`} value={choice?.displayName ?? line.displayName} onChange={(event) => update(line.lineId, { displayName: event.target.value })} />
      {line.candidates.length > 0 && <div className="review-candidates">{line.candidates.map((candidate) => <button type="button" key={candidate.foodConceptId} aria-pressed={choice?.foodConceptId === candidate.foodConceptId} onClick={() => update(line.lineId, { decision: "accept", foodConceptId: candidate.foodConceptId, displayName: candidate.displayName })}>{candidate.displayName}</button>)}</div>}
      <div className="review-actions"><button type="button" onClick={() => { setOtherLine(otherLine === line.lineId ? null : line.lineId); setConcepts([]); setConceptQuery(""); }}>Otro</button>{!pending && <button type="button" onClick={() => update(line.lineId, { decision: "unknown", foodConceptId: undefined })}>Mantener como desconocido</button>}<button type="button" onClick={() => update(line.lineId, { decision: "omit", foodConceptId: undefined })}>Omitir</button></div>
      {otherLine === line.lineId && <div className="review-other"><label>Buscar concepto<input value={conceptQuery} onChange={(event) => setConceptQuery(event.target.value)} /></label><button type="button" onClick={searchConcepts}>Buscar</button>{concepts.map((concept) => <button type="button" key={concept.foodConceptId} onClick={() => { update(line.lineId, { decision: "accept", foodConceptId: concept.foodConceptId, displayName: concept.displayName }); setOtherLine(null); }}>{concept.displayName}</button>)}{!pending && <button type="button" onClick={() => { update(line.lineId, { decision: "unknown", foodConceptId: undefined, displayName: choice.displayName }); setOtherLine(null); }}>Usar nombre libre como desconocido</button>}</div>}
    </fieldset>; })}</div>
    <button className="purchase-confirm review-submit" type="button" disabled={selected === 0 || loading || submitting || (!pending && !purchaseDate)} onClick={confirm}>{submitting ? "Guardando…" : pending ? "Guardar decisiones" : `Confirmar ${selected} ${selected === 1 ? "artículo" : "artículos"}`}</button>
  </main>;
}
