"use client";
import { FormEvent,useCallback,useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { listCachedFavorites,queueFeatureMutation } from "@/lib/favorites/db";
import { listItems } from "@/lib/inventory/db";
import { aggregateLines,deriveMissing,type ShoppingLine } from "@/lib/shopping-list/derive";
import type { MutationEnvelope } from "@/lib/favorites/types";
import { syncFeatureOutbox } from "@/lib/favorites/sync";
import styles from "./shopping-list-app.module.css";
interface ExplicitItem{ id:string;ingredient_key:string|null;name:string;quantity:number|null;unit:string|null;checked:boolean;version:number }
export function ShoppingListApp({userId}:{userId:string}){const router=useRouter();const [derived,setDerived]=useState<ShoppingLine[]>([]),[explicit,setExplicit]=useState<ExplicitItem[]>([]),[message,setMessage]=useState("");
 const load=useCallback(async()=>{const [favorites,inventory]=await Promise.all([listCachedFavorites(userId),listItems(userId)]);setDerived(aggregateLines(favorites.flatMap(f=>deriveMissing(f.snapshot.ingredients,inventory))));if(navigator.onLine){await syncFeatureOutbox(userId);const r=await fetch("/api/shopping-list");if(r.status===401){router.push("/login?error=session_expired");return}if(r.ok)setExplicit((await r.json() as {items:ExplicitItem[]}).items)}},[router,userId]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 async function mutate(item:Partial<ExplicitItem>&{name:string},desired_state:"active"|"checked"|"removed"){const clientMutationId=crypto.randomUUID(),payload={client_mutation_id:clientMutationId,item_id:item.id??crypto.randomUUID(),ingredient_key:item.ingredient_key, name:item.name,quantity:item.quantity,unit:item.unit,desired_state,expected_version:item.version};if(!navigator.onLine){await queueFeatureMutation({clientMutationId,userId,kind:"shopping",entityId:payload.item_id,payload,state:"pending",createdAt:new Date().toISOString()});setMessage("Cambio pendiente de sincronizar.");return}const r=await fetch("/api/shopping-list",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await r.json() as MutationEnvelope<ExplicitItem>;if((result.status==="applied"||result.status==="duplicate")&&result.result){setExplicit(v=>desired_state==="removed"?v.filter(x=>x.id!==result.result!.id):[...v.filter(x=>x.id!==result.result!.id),result.result!]);setMessage("Lista sincronizada")}else setMessage(`No se pudo aplicar: ${result.code}`)}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget),name=String(data.get("name")??"").trim();if(!name)return;await mutate({name,ingredient_key:null,quantity:data.get("quantity")?Number(data.get("quantity")):null,unit:String(data.get("unit")??"").trim()||null},"active");event.currentTarget.reset()}
 return <div className={styles.shell}><nav><strong>Neverita · Compra</strong><span><a href="/app/favorites">Favoritos</a><a href="/app">Inventario</a></span></nav><main><header><p>Faltantes actuales y selecciones</p><h1>Lista de compra</h1></header><p aria-live="polite">{message}</p><section><h2>Derivada de tus favoritos</h2>{derived.length?<ul>{derived.map((line,i)=><li key={`${line.ingredientKey}-${line.unit}-${i}`}><span>{line.name}</span><b>{line.quantity??"?"} {line.unit??"por definir"}</b><button onClick={()=>void mutate({name:line.name,ingredient_key:line.ingredientKey,quantity:line.quantity,unit:line.unit},"active")}>Añadir</button></li>)}</ul>:<p>No faltan ingredientes cuantificables.</p>}</section><section><h2>Selección explícita</h2><form onSubmit={submit}><input name="name" required placeholder="Ingrediente" aria-label="Ingrediente"/><input name="quantity" min="0" step="any" type="number" placeholder="Cantidad" aria-label="Cantidad"/><input name="unit" placeholder="Unidad" aria-label="Unidad"/><button>Añadir</button></form>{explicit.length?<ul>{explicit.map(item=><li key={item.id}><label><input type="checkbox" checked={item.checked} onChange={()=>void mutate(item,item.checked?"active":"checked")}/>{item.name}</label><b>{item.quantity??""} {item.unit??""}</b><button onClick={()=>void mutate(item,"removed")}>Quitar</button></li>)}</ul>:<p>Añade algo que quieras comprar.</p>}</section></main></div>}
