"use client";
import { useCallback,useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { cacheFavorite,listCachedFavorites,queueFeatureMutation } from "@/lib/favorites/db";
import type { FavoriteRecord,MutationEnvelope } from "@/lib/favorites/types";
import { listItems } from "@/lib/inventory/db";
import { syncFeatureOutbox } from "@/lib/favorites/sync";
import { buildCookingPlan } from "@/lib/cooking/plan";
import styles from "./favorites-app.module.css";
type ViewFavorite=FavoriteRecord&{availability:Array<{name:string;available:boolean}>};
export function FavoritesApp({userId}:{userId:string}){const router=useRouter();const [items,setItems]=useState<ViewFavorite[]>([]),[status,setStatus]=useState("loading"),[message,setMessage]=useState("");
 const calculate=useCallback(async(rows:FavoriteRecord[])=>{const inventory=await listItems(userId);setItems(rows.map(row=>({...row,availability:row.snapshot.ingredients.map(line=>({name:line.name,available:inventory.some(i=>(i.normalizedName??i.name).replaceAll(" ","-")===line.ingredientKey&&i.quantity>0)}))})))},[userId]);
 useEffect(()=>{let active=true;void(async()=>{try{if(!navigator.onLine)throw new Error("offline");await syncFeatureOutbox(userId);if(!active)return;const r=await fetch("/api/favorites");if(r.status===401){router.push("/login?error=session_expired");return}if(!r.ok)throw new Error();const body=await r.json() as {favorites:FavoriteRecord[]};for(const row of body.favorites)await cacheFavorite(userId,row);await calculate(body.favorites);setStatus("synced")}catch{if(!active)return;const cached=await listCachedFavorites(userId);await calculate(cached);setStatus(cached.length?"offline":"empty")}})();return()=>{active=false}},[calculate,router,userId]);
 async function remove(row:FavoriteRecord){const clientMutationId=crypto.randomUUID(),payload={client_mutation_id:clientMutationId,recipe_id:row.recipe_id,desired_state:"removed",expected_version:row.version};setMessage("Quitando…");if(!navigator.onLine){await queueFeatureMutation({clientMutationId,userId,kind:"favorite",entityId:row.id,payload,state:"pending",createdAt:new Date().toISOString()});setMessage("Quitar favorito pendiente de sincronizar.");return}const r=await fetch("/api/favorites",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await r.json() as MutationEnvelope<FavoriteRecord>;if(result.status==="applied"||result.status==="duplicate"){setItems(v=>v.filter(x=>x.id!==row.id));setMessage("Favorito eliminado")}else setMessage(result.code==="VERSION_CONFLICT"?"La receta cambió. Actualiza y vuelve a intentarlo.":"No se pudo quitar")}
 async function cook(row:ViewFavorite){const inventory=await listItems(userId);let lines;try{lines=buildCookingPlan(row.snapshot.ingredients,inventory)}catch(error){setMessage(`Revisa el plan: ${error instanceof Error?error.message:"VALIDATION_ERROR"}.`);return}const clientMutationId=crypto.randomUUID(),payload={client_mutation_id:clientMutationId,recipe_snapshot:row.snapshot,lines};setMessage(navigator.onLine?"Validando inventario…":"Cocción pendiente; el inventario no ha cambiado.");if(!navigator.onLine){await queueFeatureMutation({clientMutationId,userId,kind:"cooking",entityId:row.id,payload,state:"pending",createdAt:new Date().toISOString()});return}const r=await fetch("/api/cooking",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await r.json() as MutationEnvelope<unknown>;setMessage(result.status==="applied"||result.status==="duplicate"?"Cocción confirmada":`Conflicto: ${result.code}. Revisa el inventario y reintenta.`)}
 return <div className={styles.shell}><nav className={styles.nav}><strong>Neverita · Favoritos</strong><span><a href="/app/recipes">Recetas</a><a href="/app/shopping-list">Compra</a></span></nav><main><header><p>Tu recetario guardado</p><h1>Favoritos</h1><small>{status==="offline"?"Copia offline · disponibilidad recalculada con tu inventario local":status==="synced"?"Sincronizado":"Cargando…"}</small></header><p aria-live="polite">{message}</p>{status==="loading"?<p>Cargando favoritos…</p>:items.length===0?<section className={styles.empty}><h2>Aún no has guardado recetas</h2><a href="/app/recipes">Descubrir recetas</a></section>:<div className={styles.list}>{items.map(row=><article key={row.id}><div><h2>{row.snapshot.title}</h2><p>{row.availability.filter(x=>x.available).length} de {row.availability.length} ingredientes disponibles ahora</p></div><details><summary>Ingredientes y pasos</summary><ul>{row.availability.map(x=><li key={x.name} data-missing={!x.available}>{x.available?"✓":"+"} {x.name}</li>)}</ul><ol>{row.snapshot.instructions.map((x,i)=><li key={i}>{x}</li>)}</ol></details><div className={styles.actions}><button onClick={()=>void cook(row)}>Cocinar</button><button onClick={()=>void remove(row)}>Quitar</button></div></article>)}</div>}</main></div>}
