import type {MealEntry,MealMutation,MealPayload} from "./types";
const NAME="neverita-meal-calendar",VERSION=1,MEALS="meals",OUTBOX="outbox",META="meta",DRAFTS="drafts";
const request=<T>(r:IDBRequest<T>)=>new Promise<T>((ok,no)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});const complete=(t:IDBTransaction)=>new Promise<void>((ok,no)=>{t.oncomplete=()=>ok();t.onerror=()=>no(t.error);t.onabort=()=>no(t.error)});
export async function openMealDb(){const r=indexedDB.open(NAME,VERSION);r.onupgradeneeded=()=>{const db=r.result;const meals=db.createObjectStore(MEALS,{keyPath:"key"});meals.createIndex("by_user","userId");const out=db.createObjectStore(OUTBOX,{keyPath:"clientMutationId"});out.createIndex("by_user","userId");const drafts=db.createObjectStore(DRAFTS,{keyPath:"key"});drafts.createIndex("by_user","userId");db.createObjectStore(META,{keyPath:"key"})};return request(r)}
export async function putMeals(userId:string,rows:MealEntry[]){const db=await openMealDb(),tx=db.transaction(MEALS,"readwrite"),s=tx.objectStore(MEALS);for(const row of rows)s.put({key:`${userId}:${row.id}`,userId,...row});await complete(tx);db.close()}
export async function listMeals(userId:string){const db=await openMealDb(),tx=db.transaction(MEALS,"readonly"),rows=await request(tx.objectStore(MEALS).index("by_user").getAll(userId)) as Array<MealEntry&{userId:string}>;await complete(tx);db.close();return rows}
export async function listMutations(userId:string){const db=await openMealDb(),tx=db.transaction(OUTBOX,"readonly"),rows=await request(tx.objectStore(OUTBOX).index("by_user").getAll(userId)) as MealMutation[];await complete(tx);db.close();return rows.sort((a,b)=>a.createdAt.localeCompare(b.createdAt))}
export function compactMutations(rows:MealMutation[],next:MealMutation){const own=rows.filter(x=>x.userId===next.userId&&x.mealEntryId===next.mealEntryId),last=own.at(-1);if(!last||last.state!=="pending")return [...rows,next];if(last.operation==="create"&&next.operation==="delete")return rows.filter(x=>x.mealEntryId!==next.mealEntryId);if(last.operation==="create"&&next.operation==="update")return [...rows.filter(x=>x.clientMutationId!==last.clientMutationId),{...last,payload:next.payload}];if(last.operation==="update"&&next.operation==="update")return [...rows.filter(x=>x.clientMutationId!==last.clientMutationId),next];return [...rows,next]}
export async function queueMutation(next:MealMutation){const rows=await listMutations(next.userId),reduced=compactMutations(rows,next),db=await openMealDb(),tx=db.transaction(OUTBOX,"readwrite"),s=tx.objectStore(OUTBOX);for(const x of rows)if(!reduced.some(y=>y.clientMutationId===x.clientMutationId))s.delete(x.clientMutationId);for(const x of reduced)s.put(x);await complete(tx);db.close()}
export async function removeMutation(id:string){const db=await openMealDb(),tx=db.transaction(OUTBOX,"readwrite");tx.objectStore(OUTBOX).delete(id);await complete(tx);db.close()}
export async function saveDraft(userId:string,id:string,payload:MealPayload){const db=await openMealDb(),tx=db.transaction(DRAFTS,"readwrite");tx.objectStore(DRAFTS).put({key:`${userId}:${id}`,userId,id,payload});await complete(tx);db.close()}
export async function loadDraft(userId:string,id:string){const db=await openMealDb(),tx=db.transaction(DRAFTS,"readonly"),row=await request(tx.objectStore(DRAFTS).get(`${userId}:${id}`)) as {payload:MealPayload}|undefined;await complete(tx);db.close();return row?.payload}
export async function clearDraft(userId:string,id:string){const db=await openMealDb(),tx=db.transaction(DRAFTS,"readwrite");tx.objectStore(DRAFTS).delete(`${userId}:${id}`);await complete(tx);db.close()}
export async function setLastSync(userId:string,value:string){const db=await openMealDb(),tx=db.transaction(META,"readwrite");tx.objectStore(META).put({key:`sync:${userId}`,value});await complete(tx);db.close()}
export async function getLastSync(userId:string){const db=await openMealDb(),tx=db.transaction(META,"readonly"),row=await request(tx.objectStore(META).get(`sync:${userId}`)) as {value:string}|undefined;await complete(tx);db.close();return row?.value}
